repos:
  - repo: https://github.com/executablebooks/mdformat
    rev: 0.7.9
    hooks:
      - id: mdformat
        args: ["--number", "--table-width", "200"]
        # language_version: python3.7
        additional_dependencies:
          - mdformat-openmmlab
          - mdformat_frontmatter
          - linkify-it-py
  # - repo: local
  #   hooks:
  #     - id: update-model-index
  #       name: update-model-index
  #       description: Collect model information and update model-index.yml
  #       entry: .dev_scripts/update_model_index.py
  #       additional_dependencies: [mmengine, modelindex, tqdm, rich]
  #       language: python
  #       files: ^configs/.*\.md$
  #       require_serial: true